name: Build PumpkinMC for Android ARM64

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Update OS
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y

      - name: Clone source code
        run: |
          git clone --depth 1 --recurse-submodules --shallow-submodules -b master https://github.com/Pumpkin-MC/Pumpkin.git .
          rm rust-toolchain.toml

      - name: Setup Rust
        run: |
          rustup update
          rustup target add aarch64-linux-android

      - name: Setup Android NDK
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r30-beta3-linux.zip
          unzip -q android-ndk-r30-beta3-linux.zip -d $HOME

      - name: Compile Pumpkin
        run: |
          export NDK_PATH="$HOME/android-ndk-r30-beta3"
          export ANDROID_NDK_ROOT="$NDK_PATH"
          export ANDROID_NDK_HOME="$NDK_PATH"
          
          export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang"
          export CC_aarch64_linux_android="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang"
          export CXX_aarch64_linux_android="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang++"
          export AR_aarch64_linux_android="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"

          export CARGO_PROFILE_RELEASE_OPT_LEVEL="3"
          export CARGO_PROFILE_RELEASE_LTO="fat"
          export CARGO_PROFILE_RELEASE_CODEGEN_UNITS="1"
          export CARGO_PROFILE_RELEASE_PANIC="abort"
          export CARGO_PROFILE_RELEASE_STRIP="symbols"

          export RUSTFLAGS="-C target-feature=+aes,+neon,+lse \
                            -C opt-level=3 \
                            -C codegen-units=1 \
                            -C panic=abort \
                            -C link-arg=-Wl,-z,max-page-size=16384 \
                            -C link-arg=-Wl,--gc-sections \
                            -C link-arg=-Wl,--icf=all \
                            -C strip=symbols"
          
          cargo build --release --target=aarch64-linux-android

      - name: Upload Android Executable
        uses: actions/upload-artifact@v7
        with:
          path: target/aarch64-linux-android/release/pumpkin
          archive: false
