name: Build PumpkinMC for latest Android ARM64 nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Update OS
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y

      - name: Clone source code
        run: |
          git clone --depth 1 --recursive -b master https://github.com/Pumpkin-MC/Pumpkin.git .
          rm -f rust-toolchain.toml

      - name: Setup Rust
        run: |
          rustup update nightly
          rustup default nightly
          rustup target add aarch64-linux-android
          rustup component add rust-src

      - name: Setup Android NDK
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r30-beta3-linux.zip
          unzip -q android-ndk-r30-beta3-linux.zip -d $HOME

      - name: Compile Pumpkin
        run: |
          export NDK_PATH="$HOME/android-ndk-r30-beta3"
          export ANDROID_NDK_ROOT="$NDK_PATH"
          export ANDROID_NDK_HOME="$NDK_PATH"
          
          export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang"
          export CC_aarch64_linux_android="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang"
          export CXX_aarch64_linux_android="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang++"
          export AR_aarch64_linux_android="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
          
          export CARGO_INCREMENTAL=0

          export CARGO_PROFILE_RELEASE_LTO="fat"
          export CARGO_PROFILE_RELEASE_CODEGEN_UNITS=1
          export CARGO_PROFILE_RELEASE_PANIC="abort"

          export RUSTFLAGS="-C opt-level=3 \
                            -C codegen-units=1 \
                            -C panic=abort \
                            -C target-feature=+v9a \
                            -C link-arg=-Wl,-z,max-page-size=16384 \
                            -C strip=symbols"
          
          cargo +nightly build --release --target=aarch64-linux-android -Z build-std=std,panic_abort

      - name: Upload Android Executable
        uses: actions/upload-artifact@v7
        with:
          path: target/aarch64-linux-android/release/pumpkin
          archive: false
